name: gpu_se_cuda102

dependencies:
  - python>=3.8.2
  - numpy>=1.18.1
  - matplotlib>=3.1.3
  - tqdm>=4.46.0
  - scipy>=1.4.1
  - numba>=0.49.1
  - pandas>=1.0.3
  - cudatoolkit=10.2
  - pytorch::pytorch=1.6.0
  - pytest>=5.4.2
  - sympy>=1.5.1
  - joblib>=0.15.1
  - statsmodels>=0.11.1
  - psutil>=5.7.2
  - pip>=20.0.2
  - pip:
    - cupy_cuda102>=7.4.0
    - osqp>=0.6.1
    - sphinx>=3.2.1