name: gpu_se_cuda102

dependencies:
  - python>=3.8.1
  - numpy>=1.18.1
  - matplotlib>=3.1.3
  - tqdm>=4.40.2
  - scipy>=1.4.0
  - numba>=0.49.1
  - pandas>=1.0.2
  - pytorch::pytorch>=1.4.0
  - xlsxwriter>=1.2.8
  - oxfordcontrol::osqp>=0.6.1
  - pytest>=5.4.1
  - sympy>=1.5.1
  - joblib>=0.15.1
  - statsmodels>=0.11.1
  - psutil>=5.7.2
  - pip
  - pip:
    - cupy_cuda102>=7.4.0